"""Generate technical trading signals based on market data."""

from __future__ import annotations

from dataclasses import dataclass
import logging


@dataclass
class Signal:
    """Trading signal generated by rule evaluator."""

    asset: str
    direction: str
    reason: str
    trigger_type: str
    score: float = 1.0


def evaluate_rules(market_data: list[float]) -> list[Signal]:
    """Evaluate rules on market data and return any generated signals."""
    logging.info("Evaluating rules on %d candles", len(market_data))
    signals: list[Signal] = []
    logging.info("Rule evaluation generated %d signals", len(signals))
    return signals
