"""Generate technical trading signals based on market data."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class Signal:
    """Trading signal generated by rule evaluator."""

    asset: str
    direction: str
    reason: str
    trigger_type: str


def evaluate_rules(market_data: List[float]) -> List[Signal]:
    """Placeholder for rule evaluation logic."""
    return []
